### ISSUE TITLE
Verrou GetChar PutChar

### ISSUE THREAD

**Issue by swhatelse** [hellmak/projetSys#14]
Vérifier l'utilité du verrou supplémentaire sur GetChar et PutChar

**Comment by ThibaudB** [comment]
Il est obligatoire sinon, c'est dans le cas ou quelqu'un ferait une écriture pendant un putstring ou un putin il ne faut pas que le putchar vienne le couper. Après on parle peut être pas du même. Reprécise la ligne. Merci.

**Comment by swhatelse** [comment]
Dans syscallfunction.cc
```
void PutChar(int c){
	sc->BeginPrimitive();
	sc->SynchPutChar(c);
	sc->EndPrimitive();
}
```
```
char GetChar(){
	sc->BeginPrimitive();
	char c= sc->SynchGetChar();
	sc->EndPrimitive();
	return c;
}
```

Pour moi c'est déjà protégé dans Synch(Get/Put)Char il ne peut y avoir qu'un seul accès à la console à la fois

**Comment by hellmak** [comment]
C est pour le protéger avec putstring et putin

**Comment by hellmak** [comment]
Pour pas te trouver avec un char intempestif pendant un string ou un int
pour le put et get
Le 19 janv. 2015 08:40, "mehdi makhlouf" <makhloufmehdi1@gmail.com> a écrit
:

> C est pour le protéger avec putstring et putin
