### ISSUE TITLE
Translation adresse

### ISSUE THREAD

**Issue by swhatelse** [hellmak/projetSys#15]
Je crois qu'il y a un bug avec la virtualisation d'adresse.
Quand je fais:
```    
int u;
machine->ReadMem(vals+1, 4, &u);
```   
Je me tappe un segfault et je suis obligé de faire comme ça:
``` 
int u;
machine->ReadMem(vals+4, 1, &u);
```
C'est normal

**Comment by ThibaudB** [comment]
C'est normal, tu travaille sur un int qui est une adresse de int (pour le *4)
La segfault doit venir de la tentative d'accès à une adresse non multiple de 4 ou un truc du genre.

**Comment by swhatelse** [comment]
Ouais mais justement le deuxième argument est là pour ça non?

**Comment by hellmak** [comment]
On ne veut qu'un octet car contenant un char dans un tableau de int *4 :)
