### ISSUE TITLE
Multithreading - UserThreadCreate()

### ISSUE THREAD

**Issue by ThibaudB** [hellmak/projetSys#8]
Passage de l'argument vers StartUserThread, ainsi que la valeur de retour (-1 en cas de thread impossible à créer, manque de place dans la mémoire ? Thread::ChechOverflow ?) 
Opt : Ajout d'un identifiant pour les threads. (nom de debug)

**Comment by hellmak** [comment]
I se you! Just think to fix this you have make this ;)
